server:
  port: 8000
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
management:
  endpoint:
    env:
      enabled: true