server:
  port: 8000
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/wen-auth/dev, classpath:/config/wen-auth/prod,classpath:/config/common
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8400/eureka/